SELECT DISTINCT CAST('All' as VARCHAR) as account_type, COUNT(UID) as Count_Users_With_Missions FROM HYPEDOCS_CO.PUBLIC.USERS WHERE MISSION_TEXT is not NULL
UNION 
SELECT DISTINCT CAST('Basic' as VARCHAR) as account_type, COUNT(UID) as Count_Users_With_Missions FROM HYPEDOCS_CO.PUBLIC.USERS WHERE MISSION_TEXT is not NULL AND STATUS='BASIC'
UNION
SELECT DISTINCT CAST('Trial Ended' as VARCHAR) as account_type, COUNT(UID) as Count_Users_With_Missions FROM HYPEDOCS_CO.PUBLIC.USERS WHERE MISSION_TEXT is not NULL AND STATUS = 'TRIAL_ENDED'
UNION
SELECT DISTINCT CAST('Cancelled' as VARCHAR) as account_type, COUNT(UID) as Count_Users_With_Missions FROM HYPEDOCS_CO.PUBLIC.USERS WHERE MISSION_TEXT is not NULL AND STATUS = 'CANCELLED'